[build]
  base = "frontend"
  command = "CI= npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.16.0"
  NPM_FLAGS = "--no-optional"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  environment = { NODE_VERSION = "18.16.0" }