[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.16.0"
  NPM_FLAGS = "--no-optional"
  PYTHON_VERSION = "3.8"
  RUBY_VERSION = "2.7.1"
  GO_VERSION = "1.21"
  NODE_ENV = "production"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200